// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProductsApi.Data;

#nullable disable

namespace ProductsApi.Migrations
{
    [DbContext(typeof(ProductsApiContext))]
    [Migration("20230811060250_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ProductsApi.Models.Products", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"), 1L, 1);

                    b.Property<string>("Imageurl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Noofstocks")
                        .HasColumnType("int");

                    b.Property<string>("ProductCategory")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProductPrice")
                        .HasColumnType("int");

                    b.Property<double>("ProductRating")
                        .HasColumnType("float");

                    b.Property<string>("SellerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProductId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            Imageurl = "https://m.media-amazon.com/images/I/61FxtMZu7lL._AC_UY327_FMwebp_QL65_.jpg",
                            Noofstocks = 19,
                            ProductCategory = "Electronics",
                            ProductDescription = "Boult Audio ZCharge Bluetooth Wireless in Ear Earphones with Mic, 40H Playtime and Super Fast Charging, Environmental Noise Cancellation for Pro+ Calling and IPX5 Water Resistant (Black)",
                            ProductName = "Hearphones",
                            ProductPrice = 2500,
                            ProductRating = 1.0,
                            SellerName = "Appario Retail Private Ltd"
                        },
                        new
                        {
                            ProductId = 2,
                            Imageurl = "https://m.media-amazon.com/images/I/51+Tdu4vtgL._UX679_.jpg",
                            Noofstocks = 9,
                            ProductCategory = "Fashion",
                            ProductDescription = "White solid casual shirt, has a mandarin collar, a button placket, 1 pocket, long sleeves with roll-up tab features, curved hem",
                            ProductName = "Men White Slim Fit Casual Shirt",
                            ProductPrice = 549,
                            ProductRating = 2.5,
                            SellerName = "Maruti Enterprises"
                        },
                        new
                        {
                            ProductId = 3,
                            Imageurl = "https://tse4.mm.bing.net/th/id/OIP.cg2VMYhsCeKUvE3tp-Dm5AHaOx?w=115&h=180&c=7&r=0&o=5&dpr=1.3&pid=1.7",
                            Noofstocks = 9,
                            ProductCategory = "Electronics",
                            ProductDescription = "realme 10 Pro+ 5G (Nebula Blue, 128 GB) (8 GB RAM)",
                            ProductName = "Realme 10Pro",
                            ProductPrice = 15000,
                            ProductRating = 3.0,
                            SellerName = "Oppo Mobiles India Private Limited"
                        },
                        new
                        {
                            ProductId = 4,
                            Imageurl = "https://m.media-amazon.com/images/I/612x7+YtEBL._AC_UL480_QL65_.jpg",
                            Noofstocks = 9,
                            ProductCategory = "Home & Kitchen",
                            ProductDescription = "Vinod Bullet Stainless Steel Flask, Double Wall Insulated Steel Flask with Jacket, Hot & Cold Water Bottle 1000 ml, Silver",
                            ProductName = "Flask",
                            ProductPrice = 789,
                            ProductRating = 4.2000000000000002,
                            SellerName = "Vinod Cookware"
                        },
                        new
                        {
                            ProductId = 5,
                            Imageurl = "https://images-eu.ssl-images-amazon.com/images/I/81N7FmJhbhL._AC_UL900_SR900,600_.jpg",
                            Noofstocks = 8,
                            ProductCategory = "Books",
                            ProductDescription = "Life's Amazing Secrets: How to Find Balance and Purpose in Your Life | Inspirational Zen book on motivation, self-development & healthy living",
                            ProductName = "Life's Amazing Secrets",
                            ProductPrice = 496,
                            ProductRating = 5.0,
                            SellerName = "Penguin Ananda (8 October 2018)"
                        },
                        new
                        {
                            ProductId = 6,
                            Imageurl = "https://m.media-amazon.com/images/I/71TamRUO01L._UY879_.jpg",
                            Noofstocks = 12,
                            ProductCategory = "Watches",
                            ProductDescription = "Diesel watches reflect the confident, assertive nature of the brand itself. Bold and strong, our timepieces will blend seamlessly with any outfit you wear, throughout the year.",
                            ProductName = "Analog Black Dial Men's Watch-DZ4283",
                            ProductPrice = 19495,
                            ProductRating = 0.0,
                            SellerName = "Vee Ess Sales Pvt Ltd"
                        },
                        new
                        {
                            ProductId = 7,
                            Imageurl = " https://tse2.mm.bing.net/th/id/OIP.JDLpwKpZ6fT29FDruRiqTwHaHa?w=193&h=193&c=7&r=0&o=5&dpr=1.3&pid=1.7",
                            Noofstocks = 9,
                            ProductCategory = "Perfume",
                            ProductDescription = "Men Natural Gas-Free Long-Lasting Body Spray - 70ml",
                            ProductName = "Envy",
                            ProductPrice = 185,
                            ProductRating = 0.0,
                            SellerName = "Vini Cosmetics"
                        },
                        new
                        {
                            ProductId = 8,
                            Imageurl = "https://tse1.mm.bing.net/th/id/OIP.uvbeZacQbUB-DrnqR-koCgHaLH?pid=ImgDet&rs=1",
                            Noofstocks = 9,
                            ProductCategory = "Bags",
                            ProductDescription = "Earth-friendly, and a dependable everyday companion, the Dell Pro Slim Backpack 15 (PO1520PS) provides quality protection for your devices.",
                            ProductName = "Dell Pro Slim Backpack 15 | PO1520PS",
                            ProductPrice = 3999,
                            ProductRating = 4.2000000000000002,
                            SellerName = "Cannycom Store"
                        },
                        new
                        {
                            ProductId = 9,
                            Imageurl = "https://snpi.dell.com/snp/images/products/large/520-AAUL_MVI4.jpg",
                            Noofstocks = 9,
                            ProductCategory = "HeadPhones",
                            ProductDescription = "Experience exceptional audio clarity with this Teams certified wired headset that allows you to wear the microphone on either side for a customized fit.",
                            ProductName = "Dell Pro Stereo Headset | WH3022",
                            ProductPrice = 2500,
                            ProductRating = 4.2000000000000002,
                            SellerName = "gadgets storm"
                        },
                        new
                        {
                            ProductId = 10,
                            Imageurl = "amazon.com/images/I/716SnsvjetL._AC_UY327_FMwebp_QL65_.jpg",
                            Noofstocks = 9,
                            ProductCategory = "Monitors",
                            ProductDescription = "Feature Height Adjustment, Anti Glare Screen, Pivot Adjustment, USB Hub, High Dynamic Range, Feature	Height Adjustment, Anti Glare Screen, Pivot Adjustment, USB Hub, High Dynamic Range",
                            ProductName = "Dell 27 QHD Monitor (USB-C) | S2722DC",
                            ProductPrice = 15999,
                            ProductRating = 4.2000000000000002,
                            SellerName = "BenQ, BenQ Corporation 16 Jihu Road, Neihu 114, Taipei, Taiwan"
                        },
                        new
                        {
                            ProductId = 11,
                            Imageurl = "https://img3.junaroad.com/uiproducts/13844456/zoom_1-1499510462.jpg",
                            Noofstocks = 10,
                            ProductCategory = "Watches",
                            ProductDescription = "Case style: Analog watch with a stainless steel circular case Dial style: Black dial with silver hands Strap style: Stainless steel strap with a butterfly clasp for comfort and style Features: Branding in silver at twelve hour mark and Roman numeral marks through out rest of dial Screw to reset time",
                            ProductName = "Titan Women Black Dial Watch",
                            ProductPrice = 3165,
                            ProductRating = 4.0,
                            SellerName = "VRP Telematics"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
